name: build index.js

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3.5.1
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
                  node-version: 16.x
                  cache: "npm"
            - name: Create local changes
              run: |
                  npm ci
                  npm run build --if-present
            - name: Commit files
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add ./dist/index.js
                  git commit -m "BUILD: Build index.js"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
