name: RunFairSECO

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    RunFairSECO:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./
            - uses: actions/upload-artifact@v3
              with:
                  name: FairSECO Result
                  path: .FairSECO/
